version: 2.1

jobs:
  build-and-test:
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            ./firstTimeSetup.sh
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            python setup.py develop

workflows:
  main:
    jobs:
      - build-and-test
